<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCAeL7wF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCAeL7wF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCAeL7wF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCAeL7wF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCAeL7wF\App_KernelDevDebugContainer([
    'container.build_hash' => 'CAeL7wF',
    'container.build_id' => '6c9d8c89',
    'container.build_time' => 1715267875,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCAeL7wF');
